-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 12:17:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema battlebot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema battlebot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `battlebot` DEFAULT CHARACTER SET utf8 ;
USE `battlebot` ;

-- -----------------------------------------------------
-- Table `battlebot`.`Battlebot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlebot`.`Battlebot` (
  `Battlebot_ID` INT NOT NULL AUTO_INCREMENT,
  `Botgeluidje` VARCHAR(350) NULL,
  `Botnaam` VARCHAR(30) NOT NULL,
  `Spel_1` INT NULL DEFAULT 0,
  `Spel_2` INT NULL DEFAULT 0,
  `Spel_3` INT NULL DEFAULT 0,
  `Spel_4` INT NULL DEFAULT 0,
  `Spel_5` INT NULL DEFAULT 0,
  `Totaalpunten` INT NULL DEFAULT 0,
  `Afbeeldingpath` VARCHAR(500) NULL,
  PRIMARY KEY (`Battlebot_ID`),
  UNIQUE INDEX `Groepnaam_UNIQUE` (`Botnaam` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battlebot`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlebot`.`User` (
  `User_ID` INT NULL AUTO_INCREMENT,
  `Gebruikersnaam` VARCHAR(45) NULL,
  `Wachtwoord` VARCHAR(150) NULL,
  `Websitefunctie` VARCHAR(45) NULL,
  `Battlebot_Battlebot_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC),
  INDEX `fk_User_Battlebot_idx` (`Battlebot_Battlebot_ID` ASC),
  CONSTRAINT `fk_User_Battlebot`
  FOREIGN KEY (`Battlebot_Battlebot_ID`)
  REFERENCES `battlebot`.`Battlebot` (`Battlebot_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battlebot`.`Leden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlebot`.`Leden` (
  `Lid_ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NULL,
  `Achternaam` VARCHAR(45) NULL,
  `Groepsfunctie` VARCHAR(45) NULL,
  `Battlebot_Battlebot_ID` INT NOT NULL,
  PRIMARY KEY (`Lid_ID`),
  UNIQUE INDEX `Lid_ID_UNIQUE` (`Lid_ID` ASC),
  INDEX `fk_Leden_Battlebot1_idx` (`Battlebot_Battlebot_ID` ASC),
  CONSTRAINT `fk_Leden_Battlebot1`
  FOREIGN KEY (`Battlebot_Battlebot_ID`)
  REFERENCES `battlebot`.`Battlebot` (`Battlebot_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/*Battlebots invoer:*/
INSERT INTO `battlebot` (`Battlebot_ID`, `Botgeluidje`, `Botnaam`, `Totaalpunten`, `Afbeeldingpath`) VALUES (NULL, NULL, 'INF1F1A', NULL, NULL);
INSERT INTO `battlebot` (`Battlebot_ID`, `Botgeluidje`, `Botnaam`, `Totaalpunten`, `Afbeeldingpath`) VALUES (NULL, NULL, 'INF1F1B', NULL, NULL);
INSERT INTO `battlebot` (`Battlebot_ID`, `Botgeluidje`, `Botnaam`, `Totaalpunten`, `Afbeeldingpath`) VALUES (NULL, NULL, 'INF1F2A', NULL, NULL);
INSERT INTO `battlebot` (`Battlebot_ID`, `Botgeluidje`, `Botnaam`, `Totaalpunten`, `Afbeeldingpath`) VALUES (NULL, NULL, 'INF1F2B', NULL, NULL);
INSERT INTO `battlebot` (`Battlebot_ID`, `Botgeluidje`, `Botnaam`, `Totaalpunten`, `Afbeeldingpath`) VALUES (NULL, NULL, 'Camera', NULL, NULL);

/*Klas invoer:*/
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Ernst-Jan', 'Bakker', 'Website', '1');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Michiel', 'Jansen', 'Battlebot', '1');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Soner', 'Mulder', 'Battlebot', '1');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Edris', 'Bahman', 'Netwerkbeheerder', '1');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Thierry', 'de Groot', 'Battlebot', '2');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Rianne', 'Lubberink', 'Battlebot', '2');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Myrren', 'van Belkom', 'Netwerkbeheerder', '2');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Sander', 'Paping', 'Website', '2');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Lennart', 'Pikijn', 'Battlebot', '2');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Niek', 'Luttikhof', 'Website', '3');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Yaron', 'Lambers', 'Netwerkbeheerder', '3');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Thomas', 'Christerus', 'Battlebot', '3');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Tim', 'Zuiderveld', 'Battlebot', '3');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Dennis', 'Boer', 'Battlebot', '4');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Justin', 'Westerling', 'Website', '4');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Kevin', 'Hekman', 'Netwerkbeheerder', '4');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Maartje', 'Kok', 'Battlebot', '4');
INSERT INTO `leden` (`Lid_ID`, `Naam`, `Achternaam`, `Groepsfunctie`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'David', 'Dorenbos', 'Battlebot', '4');

/*Spellen invoer:
INSERT INTO `spel` (`Spel_ID`, `Naam`, `Positie`, `Punten`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Sumo', NULL, NULL, NULL);
INSERT INTO `spel` (`Spel_ID`, `Naam`, `Positie`, `Punten`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Obstakelrace', NULL, NULL, NULL);
INSERT INTO `spel` (`Spel_ID`, `Naam`, `Positie`, `Punten`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Dansen', NULL, NULL, NULL);
INSERT INTO `spel` (`Spel_ID`, `Naam`, `Positie`, `Punten`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'Race', NULL, NULL, NULL);
INSERT INTO `spel` (`Spel_ID`, `Naam`, `Positie`, `Punten`, `Battlebot_Battlebot_ID`) VALUES (NULL, 'ABC-Race', NULL, NULL, NULL);
*/