-- MySQL Script generated by MySQL Workbench
-- Wed Sep 27 15:48:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema battlebot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema battlebot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `battlebot` DEFAULT CHARACTER SET utf8 ;
USE `battlebot` ;

-- -----------------------------------------------------
-- Table `battlebot`.`Battlebot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlebot`.`Battlebot` (
  `Battlebot_ID` INT NULL AUTO_INCREMENT,
  `Botgeluidje` VARCHAR(350) NULL,
  `Botnaam` VARCHAR(30) NOT NULL,
  `Totaalpunten` INT NULL,
  `Afbeeldingpath` VARCHAR(500) NULL,
  PRIMARY KEY (`Battlebot_ID`),
  UNIQUE INDEX `Groepnaam_UNIQUE` (`Botnaam` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battlebot`.`Spel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlebot`.`Spel` (
  `Spel_ID` INT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(100) NOT NULL,
  `Positie` INT NULL,
  `Punten` INT NULL,
  `Battlebot_Battlebot_ID` INT NOT NULL,
  PRIMARY KEY (`Spel_ID`),
  UNIQUE INDEX `Naam_UNIQUE` (`Naam` ASC),
  INDEX `fk_Spel_Battlebot1_idx` (`Battlebot_Battlebot_ID` ASC),
  CONSTRAINT `fk_Spel_Battlebot1`
  FOREIGN KEY (`Battlebot_Battlebot_ID`)
  REFERENCES `battlebot`.`Battlebot` (`Battlebot_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battlebot`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlebot`.`User` (
  `User_ID` INT NULL AUTO_INCREMENT,
  `Gebruikersnaam` VARCHAR(45) NULL,
  `Wachtwoord` VARCHAR(150) NULL,
  `Websitefunctie` VARCHAR(45) NULL,
  `Battlebot_Battlebot_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC),
  INDEX `fk_User_Battlebot_idx` (`Battlebot_Battlebot_ID` ASC),
  CONSTRAINT `fk_User_Battlebot`
  FOREIGN KEY (`Battlebot_Battlebot_ID`)
  REFERENCES `battlebot`.`Battlebot` (`Battlebot_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `battlebot`.`Leden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `battlebot`.`Leden` (
  `Lid_ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NULL,
  `Achternaam` VARCHAR(45) NULL,
  `Groepsfunctie` VARCHAR(45) NULL,
  `Battlebot_Battlebot_ID` INT NOT NULL,
  PRIMARY KEY (`Lid_ID`),
  UNIQUE INDEX `Lid_ID_UNIQUE` (`Lid_ID` ASC),
  INDEX `fk_Leden_Battlebot1_idx` (`Battlebot_Battlebot_ID` ASC),
  CONSTRAINT `fk_Leden_Battlebot1`
  FOREIGN KEY (`Battlebot_Battlebot_ID`)
  REFERENCES `battlebot`.`Battlebot` (`Battlebot_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
